name: Self-hosted runner using custom Docker image

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted

    container:
      image: nehama1020/py-docker-base-hello:latest

    steps:
      - name: Run Python in container on self-hosted runner
        run: python3 /app/app.py

